Repository OSGeo/OSGeoLive-doc, pull requests merged in 2020-10, with the labels that each got.

#595 update rasdaman version for OSGeoLive 14
  projects_info.csv
Labels: wait for installer

#627 Name of view corrected.
  doc/quickstart/openjump_quickstart.rst
Labels: typo-fix

#629 Add required package to build doc on Ubuntu 20.04 Focal Fossa
  README.rst
Labels: Update

#630 virtualization_quickstart.rst updates
  doc/quickstart/virtualization_quickstart.rst
Labels: enhancement

#604 Add geostyler doc
  .tx/config
  contributors.csv
  doc/images/projects/geostyler/geostyler_screenshot.png
  doc/images/projects/geostyler/logo_geostyler.png
  doc/images/projects/geostyler/quickstart_compact.png
  doc/overview/geostyler_overview.rst
  doc/quickstart/geostyler_quickstart.rst
  projects_info.csv
Labels: wait for installer

#621 Adding the Re3gistry files
  doc/images/projects/re3gistry/logo_re3gistry.png
  doc/images/projects/re3gistry/re3gistry_screenshot.png
  doc/overview/re3gistry_overview.rst
  doc/quickstart/re3gistry_quickstart.rst
  projects_info.csv
Labels: wait for installer

#622 Updating the INSPIRE overview file and adding the INSPIRE screenshot
  doc/images/projects/inspire/inspire_screenshot.png
  doc/overview/inspire_overview.rst
Labels: wait for installer

#635 [re3gistry] fixing indentation
  doc/overview/re3gistry_overview.rst
Labels: bug-fix
