Repository OSGeo/OSGeoLive-doc, pull requests merged in 2021-01, with the labels that each got.

#661 Commandline generation
  doc/conf.py
  doc/index.rst
  doc/quickstart/CMakeLists.txt
  doc/quickstart/eoxserver_quickstart.rst
Labels: bug-fix

#667 fixed Operating System typo
  doc/quickstart/commandline_quickstart.rst
Labels: typo-fix

#674 Pgrouting update
  .tx/config
  doc/images/projects/pgrouting/pgrouting_screenshot.png
  doc/overview/pgrouting_overview.rst
  doc/quickstart/pgrouting_quickstart.rst
  locale/README.md
  locale/en/LC_MESSAGES/overview/pgrouting_overview.po
  locale/en/LC_MESSAGES/quickstart/commandline_quickstart.po
  locale/en/LC_MESSAGES/quickstart/mapnik_quickstart.po
  locale/en/LC_MESSAGES/quickstart/osm_quickstart.po
  locale/en/LC_MESSAGES/quickstart/pgrouting_quickstart.po
  locale/en/LC_MESSAGES/sponsors.po
  locale/pot/overview/pgrouting_overview.pot
  locale/pot/quickstart/commandline_quickstart.pot
  locale/pot/quickstart/mapnik_quickstart.pot
  locale/pot/quickstart/osm_quickstart.pot
  locale/pot/quickstart/pgrouting_quickstart.pot
  locale/pot/sponsors.pot
  projects_info.csv
Labels: Update, locale
